name: Rust

on:
  repository_dispatch:
    types: [build]
  workflow_dispatch:
      inputs:
        name:
          description: 'Run?'
          required: true
          default: 'YES!'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: hecrj/setup-rust-action@master
      with:
        rust-version: stable
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: npm install -g yarn
    - uses: actions/checkout@v2
    - name: Rust set up
      run: |
        set path="%USERPROFILE%\.cargo\bin"
        rustup self update
        rustup update
        rustup install nightly
    - name: Run test build for thingy
      run: cargo +nightly build --release
    - name: Archive bin
      run: |
        cd target/release 
        7z -tzip a GM8Emulator.zip * -mx0 | grep ing 
        cd ../..
        mv target/release/GM8Emulator.zip .
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
          path: GM8Emulator.zip
